### ISSUE TITLE
Load bell schedule data to database or JSON files

### ISSUE THREAD

**Issue by AlpriElse** [AlpriElse/Maine-Dashboard#3]

**Comment by xXLabRatXx** [comment]
@AlpriElse Should the times be in the old format, or a 4 digit 24-hour time (7:45 AM is 0745)? The 24 hour time would be easily read by humans and you can get the hour/minute by the first 2 characters/the last 2.
What do you think?

**Comment by AlpriElse** [comment]
Take a look at MomentJS (https://momentjs.com/docs/#/parsing/utc/)

I want to start using a more standardized way of storing times and UTC looks like a good approach.

**Comment by AlpriElse** [comment]
We could use JSON files for now, but I'd like to move to a database-backed system in the future.

**Comment by AlpriElse** [comment]
Created temp.json in ~/src/server/api/ in place of mongoDB database.
